cds assert
cap-js/graphql pull request #161
Opened 2024-03-12 12:37 UTC by SamuelBrucksch

2024-03-12 13:02 UTC, schwma requested changes

2024-03-12 16:59 UTC, sjvans commented on test/tests/error-handling-prod.test.js
> +        // REVISIT: message missing, cds.assert also misses some properties like type, element, entity ...
see https://github.com/cap-js/graphql/pull/162

2024-03-13 09:51 UTC, SamuelBrucksch commented on test/tests/error-handling-prod.test.js
> +
```suggestion
```

2024-03-13 09:53 UTC, SamuelBrucksch commented on CHANGELOG.md
> +
```suggestion
```

2024-03-13 09:55 UTC, SamuelBrucksch commented on lib/resolvers/crud/update.js
> +  // REVISIT: should cds.assert be enabled by default?
```suggestion
```

2024-03-13 09:55 UTC, SamuelBrucksch commented on lib/resolvers/crud/create.js
> +  // REVISIT: should cds.assert be enabled by default?
```suggestion
```

2024-03-13 16:44 UTC, schwma approved these changes

2024-03-20 12:38 UTC, schwma commented
Can we merge this?

2024-03-28 15:34 UTC, merged